-- AlterTable
ALTER TABLE `order` MODIFY `productionStatus` ENUM('CART', 'PENDING', 'DRIED', 'PATTERN_CONFIRMED', 'RESIN_CURED', 'SHIPPED') NOT NULL DEFAULT 'CART',
    MODIFY `paymentStatus` ENUM('UNPAID', 'HALF_PAID', 'FULL_PAID') NOT NULL DEFAULT 'UNPAID';
