-- AlterTable
ALTER TABLE `order` MODIFY `productionStatus` ENUM('CART', 'PENDING', 'DRIED', 'PATTERN_CONFIRMED', 'RESIN_CURED', 'SHIPPED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `orderitem` MODIFY `status` ENUM('CART', 'PENDING', 'DRIED', 'PATTERN_CONFIRMED', 'RESIN_CURED', 'SHIPPED') NOT NULL DEFAULT 'PENDING';
